version: "3.9" 

# ./teamcity-pgdata - Posgres DB data
# ./teamcity-datadir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./teamcity-agent/conf - configuration directory for agent

# ./nexus-data - Nexus data directory

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./teamcity-pgdata:/var/lib/postgresql/data
    ports:
      - 9000:5432

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    volumes:
      - ./teamcity-datadir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - ./teamcity-agent/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - teamcity

  nexus:
    image: sonatype/nexus3:${NEXUS_VERSION}
    restart: always
    ports:
      - 8081:8081  # nexus
      - 8082:8082  # hosted
      - 8083:8083  # group
    volumes:
      - ./nexus-data:/nexus-data
